src/views/SignCla.vue

fix lang empty

---

src/components/NewFooter.vue
src/store/index.js
src/views/ConfigCheck.vue
src/views/CorporationList.vue
src/views/Index.vue
src/views/LinkedRepo.vue
src/views/SignCla.vue
src/views/SignType.vue

clear unuse mutation and state

---

src/store/index.js
src/views/SignCla.vue
src/views/SignType.vue

fix cahce cla pdf

---

src/components/NewHeader.vue
src/util/util.js

adapter stable4 localStorage lang

---

src/views/Subemail.vue

modify subemail table head desc

---

public/static/const-config.js
src/components/NewHeader.vue
src/util/util.js
src/views/CorporationManagerLogin.vue
src/views/LoginTypeSelect.vue
src/views/SignType.vue

企业管理员登陆入口迁移到社区签署首页中，管理员登特定社区，登陆接口需要增加平台，组织，仓库信息。

move corp login to sign index

---

public/static/const-config.js

clear conflict

---

src/views/SignCla.vue

修复签署页跳转到隐私声明页面之后，切换语言，再返回到签署页导致无法点击发送验证码的bug

fix send code bug

---

public/static/const-config.js
public/static/lang/en-us.js
public/static/lang/zh-cn.js
src/util/util.js
src/views/AddCorpUrl.vue
src/views/AddIndividualUrl.vue
src/views/ConfigFields.vue
src/views/CorporationList.vue

限制社区管理员配置CLA信息收集字段的范围，个人CLA固定两个字段，不可配置其他字段，企业CLA默认有4个字段，另外提供3种自定义选择，并优化字段对语言的自适应更改

limit cla field

---

public/static/const-config.js
public/static/lang/en-us.js
src/components/NewHeader.vue
src/store/index.js
src/util/api.js
src/util/util.js
src/views/CorporationManagerLogin.vue
src/views/LinkedRepo.vue
src/views/SignCla.vue
src/views/SignType.vue

change params linkid

---

src/views/ConfigCla.vue

fix add corp cla check page title

---

src/views/SignCla.vue

fix get date

---

src/assets/css/global.css
src/views/CorporationList.vue
src/views/CreateManager.vue
src/views/EmployeeList.vue
src/views/ManagerList.vue
src/views/RootManager.vue
src/views/SignedRepo.vue
src/views/Subemail.vue

rename createmanamge page button class

---

public/static/const-config.js
src/router/index.js
src/views/SignType.vue

Adapter old linkid

---

src/router/index.js
src/util/util.js
src/views/Index.vue
src/views/JumpPage.vue
src/views/LoginTypeSelect.vue
vue.config.js

Corp entry jump

---

src/views/LinkedRepo.vue

modify org table width

---

src/views/CorporationList.vue

modify upload pdf loading close

---

src/components/NewHeader.vue
src/util/util.js

Modify header menu

---

public/static/lang/en-us.js
public/static/lang/zh-cn.js
src/assets/css/global.css
src/components/HttpButton.vue
src/util/util.js
src/views/ConfigCheck.vue
src/views/ConfigEmail.vue
src/views/CorporationList.vue
src/views/CorporationManagerLogin.vue
src/views/LinkedRepo.vue
src/views/PlatformSelect.vue
src/views/SignCla.vue

Dev http button

---

public/static/lang/zh-cn.js
src/views/SignCla.vue

password verify

---

public/static/const-config.js
src/components/NewHeader.vue
src/components/SignReLoginDialog.vue
src/components/SignSuccessDialog.vue
src/views/JumpPage.vue
src/views/LinkedRepo.vue
src/views/SignType.vue

remove sign link

---

src/views/SignCla.vue

back signpage set height

---

src/router/index.js
src/util/util.js

add page type

---

public/index.html
public/static/const-config.js
src/main.js

Modify static file cache

---

src/views/SignType.vue

modify sign guide

---

public/static/const-config.js
src/router/index.js
src/views/SignType.vue

hidden lookeng linkid
